name: Build System

on: workflow_dispatch

jobs:

  build:
    runs-on: ubuntu-20.04
    steps:

    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'

    - name: Checkout
      uses: actions/checkout@master
    
    - name: Build
      run: |
        ls -al
        sudo chmod +x ./run_ci.sh
        cd devices/eon
        sudo ../../run_ci.sh
      shell: bash
